"""empty message

Revision ID: 36d13620b060
Revises: db658d740ac0
Create Date: 2025-04-30 13:00:41.130292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36d13620b060'
down_revision = 'db658d740ac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.drop_constraint('blog_usuario_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['usuario_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('comentario', schema=None) as batch_op:
        batch_op.drop_constraint('comentario_blog_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('comentario_usuario_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'blog', ['blog_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['usuario_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('foto',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('foto',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('comentario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comentario_usuario_id_fkey', 'user', ['usuario_id'], ['id'])
        batch_op.create_foreign_key('comentario_blog_id_fkey', 'blog', ['blog_id'], ['id'])

    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('blog_usuario_id_fkey', 'user', ['usuario_id'], ['id'])

    # ### end Alembic commands ###
