"""empty message

Revision ID: 8da728303888
Revises: bca46ed8a5bb
Create Date: 2025-04-23 20:13:55.326024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8da728303888'
down_revision = 'bca46ed8a5bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.alter_column('usuario',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Integer(),
               nullable=False)
        batch_op.create_foreign_key(None, 'user', ['usuario'], ['id'])

    with op.batch_alter_table('comentario', schema=None) as batch_op:
        batch_op.alter_column('usuario',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Integer(),
               nullable=False)
        batch_op.create_foreign_key(None, 'user', ['usuario'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('usuario',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=30),
               nullable=True)

    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('usuario',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=30),
               nullable=True)

    # ### end Alembic commands ###
