"""empty message

Revision ID: bca46ed8a5bb
Revises: 2cbdbd11862c
Create Date: 2025-04-23 18:15:20.459890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bca46ed8a5bb'
down_revision = '2cbdbd11862c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=30), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('titulo', sa.String(length=50), nullable=True),
    sa.Column('cuerpo', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=30), nullable=True),
    sa.Column('contraseña', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=30), nullable=True),
    sa.Column('cuerpo', sa.String(length=1000), nullable=True),
    sa.Column('blog_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comentario')
    op.drop_table('user')
    op.drop_table('blog')
    # ### end Alembic commands ###
