"""empty message

Revision ID: c679a06c89c8
Revises: 2dca48717b29
Create Date: 2025-04-23 11:17:39.338093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c679a06c89c8'
down_revision = '2dca48717b29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=30), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('titulo', sa.String(length=50), nullable=True),
    sa.Column('cuerpo', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog')
    # ### end Alembic commands ###
