"""empty message

Revision ID: db658d740ac0
Revises: d3ad4ff6d5f8
Create Date: 2025-04-30 12:55:02.731077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db658d740ac0'
down_revision = 'd3ad4ff6d5f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.drop_constraint('blog_usuario_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['usuario_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('comentario', schema=None) as batch_op:
        batch_op.drop_constraint('comentario_blog_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('comentario_usuario_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'blog', ['blog_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['usuario_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comentario_usuario_id_fkey', 'user', ['usuario_id'], ['id'])
        batch_op.create_foreign_key('comentario_blog_id_fkey', 'blog', ['blog_id'], ['id'])

    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('blog_usuario_id_fkey', 'user', ['usuario_id'], ['id'])

    # ### end Alembic commands ###
